[tool.poetry]
name = "project-template"
version = "0.1.0"
description = ""
authors = ["MegMM <mm_reads@live.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
